### ISSUE TITLE
when I execute the command: python3 build.py -DVOLE_PSI_ENABLE_BOOST=ON, error occurs. The following are error messages:

### ISSUE THREAD

**Issue by seven7-qiqi** [Visa-Research/volepsi#84]
when I execute the command: python3 build.py -DVOLE_PSI_ENABLE_BOOST=ON, error occurs. The following are error messages:

![Image](https://github.com/user-attachments/assets/5674b190-1629-4c9a-b21a-10b42240885c)
 
How solve it?

**Comment by ladnir** [comment]
Can you do the following.

1. Delete `out/`
2. `python3 build.py -DVOLE_PSI_ENABLE_BOOST=ON`
3. Post here the **full** output of 2, everything from the start of the command to when it errors.

**Comment by ladnir** [comment]
actually i was able to reproduce. I'll push a fix.

**Comment by seven7-qiqi** [comment]
> 实际上我能够复制。我会推送一个修复程序。


Do I still need to output the complete error message?

**Comment by seven7-qiqi** [comment]
Hope to wait for your repair as soon as possible, thank you!

**Comment by ladnir** [comment]
ok, the so to fix it you can 

1. delete `out/`
2. open to `thirdparty/getLibOTe.cmake`
3. change the `GIT_TAG` value to `d55867114c78272be7142bd67ebdcb346fec8621`
4. `python3 build.py -DVOLE_PSI_ENABLE_BOOST=ON`

I'll push these changes but it might take me a few hours or tomorrow at the latest.

**Comment by seven7-qiqi** [comment]
> 好的，所以你可以修复它
> 
> 1. 删除`out/`
> 2. 开放对象`thirdparty/getLibOTe.cmake`
> 3. 将值更改为`GIT_TAG``d55867114c78272be7142bd67ebdcb346fec8621`
> 4. `python3 build.py -DVOLE_PSI_ENABLE_BOOST=ON`
> 
> 我会推送这些更改，但可能需要几个小时或最迟明天。

Thank you very much for your answer.

**Comment by seven7-qiqi** [comment]
Professor, I have another question, Boxos is an implementation of OKVS for the promotion in RR22, and Paxos is the implementation of Paxos in PRTY20, is that so?

**Comment by RindalVisa** [comment]
should be fixed.

**Comment by seven7-qiqi** [comment]
> 好的，所以你可以修复它
> 
> 1. 删除`out/`
> 2. 开放对象`thirdparty/getLibOTe.cmake`
> 3. 将值更改为`GIT_TAG``d55867114c78272be7142bd67ebdcb346fec8621`
> 4. `python3 build.py -DVOLE_PSI_ENABLE_BOOST=ON`
> 
> 我会推送这些更改，但可能需要几个小时或最迟明天。

Professor, I'm now re-downloading to compile and still get the error from last time. Two weeks ago it was modified with your help and it compiled successfully, and now I get the same error again.（Environment: unbuntu 20.04）
![Image](https://github.com/user-attachments/assets/e63f25e6-fb2c-4c84-b577-76631c4be4a6)
